AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  VpcId:
    Type: String
  Subnets:
    Type: String
  InstanceType:
    Type: String
    Default: t2.micro
  KeyPairName:
    Type: String
  SourceBucket:
    Type: String
  SourceKey:
    Type: String

Resources:

  ContactsDynamoDBTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "Email"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "Email"
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  BeanstalkIamInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    DependsOn:
    - BeanstalkIAMRole
    Properties:
      Path: /
      Roles:
      - !Ref BeanstalkIAMRole

  BeanstalkIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: Allow-Put-Into-DynamoDB
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - dynamodb:PutItem
            Resource: !Sub '${ContactsDynamoDBTable.Arn}'

  BeanstalkApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      Description: AWS Elastic Beanstalk Beanstalk Application
  BeanstalkApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName:
        Ref: BeanstalkApplication
      Description: AWS ElasticBeanstalk Beanstalk Application Version
      SourceBundle:
        S3Bucket: !Ref SourceBucket
        S3Key: !Ref SourceKey
  BeanstalkConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName:
        Ref: BeanstalkApplication
      Description: AWS ElasticBeanstalk Beanstalk Configuration Template
      OptionSettings:
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: TABLENAME
        Value: !Ref ContactsDynamoDBTable
      - Namespace: aws:autoscaling:asg
        OptionName: MinSize
        Value: '1'
      - Namespace: aws:autoscaling:asg
        OptionName: MaxSize
        Value: '2'
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: EnvironmentType
        Value: LoadBalanced
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: EC2KeyName
        Value: !Ref KeyPairName
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: IamInstanceProfile
        Value: !Ref BeanstalkIamInstanceProfile
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: InstanceType
        Value: !Ref InstanceType  
      - Namespace: aws:ec2:vpc
        OptionName: VPCId
        Value: !Ref VpcId
      - Namespace: aws:ec2:vpc
        OptionName: Subnets
        Value: !Ref Subnets
      SolutionStackName: 64bit Amazon Linux 2017.03 v2.5.2 running Python 3.4
  BeanstalkEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName:
        Ref: BeanstalkApplication
      Description: AWS ElasticBeanstalk Beanstalk Environment
      TemplateName:
        Ref: BeanstalkConfigurationTemplate
      VersionLabel:
        Ref: BeanstalkApplicationVersion

Outputs:

  AppEndpoint:
    Value: !GetAtt BeanstalkEnvironment.EndpointURL
    Description: Endpoint for Elastic Beanstalk application
  DynamoDBArn:
    Value: !GetAtt ContactsDynamoDBTable.Arn
    Description: DynamoDB table full ARN
  DynamoDBTableName:
    Value: !Ref ContactsDynamoDBTable
    Description: DynamoDB table name only

