AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Sample architecture using Field-Level Encryption feature of Amazon CludFront
  You will be billed for the AWS resources used if you create a stack from this template.
  **NOTICE** Copyright 2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
  Licensed under the Apache License, Version 2.0 (the "License").
  You may not use this file except in compliance with the License.
  A copy of the License is located at http://www.apache.org/licenses/LICENSE-2.0 or in the "license" file accompanying this file.
  This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
  either express or implied. See the License for the specific language governing permissions and limitations under the License.

Parameters:
  KeyPairName:
    Description: Name of an existing EC2 KeyPair to enable SSH access.
    Type: AWS::EC2::KeyPair::KeyName
  RemoteAccessCIDR:
    Description: Only connections from this network are allowed SSH acces to bastion host.
      E.g. 92.198.130.0/24. To allow access from anywhere use 0.0.0.0/0
    Type: String
    Default: 0.0.0.0/0
    AllowedPattern: ^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?).){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: 'Must be IPv4 CIDR notation: X.X.X.X/X'
  VpcCIDR:
    Description: Please provide a CIDR block to be used by the Applicatoin VPC.  The Application VPC will host your application servers and Sophos OGW instances.
    Type: String
    Default: 10.100.0.0/16
    AllowedPattern: ^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?).){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: 'Must be IPv4 CIDR notation: X.X.X.X/X'
  Subnet1CIDR:
    Description: CIDR block for a public subnet in the first availability zone
    Type: String
    Default: 10.100.1.0/24
    AllowedPattern: ^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?).){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: 'Must be IPv4 CIDR notation: X.X.X.X/X'
  Subnet2CIDR:
    Description: CIDR block for a public subnet in the second availability zone
    Type: String
    Default: 10.100.2.0/24
    AllowedPattern: ^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?).){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: 'Must be IPv4 CIDR notation: X.X.X.X/X'
  TemplatesBucket:
    Description: S3 bucket with CloudFormation templates for nested stacks
    Type: String
    Default: atomic-templates
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: TemplatesBucket S3 bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-).
  TemplatesPrefix:
    Description: Path in the S3 bucket containing CloudFormation templates
    Type: String
    Default: field-encryption/
    AllowedPattern: ^[0-9a-zA-Z-/]*$
    ConstraintDescription: TemplatesPrefix key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/).
  ArtifactsBucket:
    Description: S3 bucket with artifact files (zip files with app code)
    Type: String
    Default: atomic-artifacts
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: ArtifactsBucket S3 bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-).
  ArtifactsPrefix:
    Description: Path in the S3 bucket containing artifact files
    Type: String
    Default: field-encryption/
    AllowedPattern: ^[0-9a-zA-Z-/]*$
    ConstraintDescription: TemplatesPrefix key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/).    


Resources:

  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplatesBucket}/${TemplatesPrefix}vpc.yaml
      Parameters:
        Name:         !Ref AWS::StackName
        VpcCIDR:      !Ref VpcCIDR
        Subnet1CIDR:  !Ref Subnet1CIDR
        Subnet2CIDR:  !Ref Subnet2CIDR

  ElasticBeanstalk:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplatesBucket}/${TemplatesPrefix}elastic-beanstalk.yaml
      Parameters:        
        VpcId:          !GetAtt VPC.Outputs.VpcId
        Subnets:        !GetAtt VPC.Outputs.Subnets
        InstanceType:   t2.micro
        KeyPairName:    !Ref KeyPairName
        SourceBucket:   !Ref ArtifactsBucket
        SourceKey:      !Sub ${ArtifactsPrefix}app.zip

  BastionHost:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplatesBucket}/${TemplatesPrefix}linux-bastion.json
      Parameters:        
        VPCID:              !GetAtt VPC.Outputs.VpcId
        PublicSubnet1ID:    !GetAtt VPC.Outputs.Subnet1ID
        PublicSubnet2ID:    !GetAtt VPC.Outputs.Subnet2ID
        KeyPairName:        !Ref KeyPairName
        RemoteAccessCIDR:   !Ref RemoteAccessCIDR
        DynamoDBArn:        !GetAtt ElasticBeanstalk.Outputs.DynamoDBArn
        DynamoDBTableName:  !GetAtt ElasticBeanstalk.Outputs.DynamoDBTableName
        ScriptsURL:         !Sub https://s3.amazonaws.com/${ArtifactsBucket}/${TemplatesPrefix}scripts.zip
        CloudFrontDistribution: !Ref CloudFrontDistribution


  CloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !GetAtt ElasticBeanstalk.Outputs.AppEndpoint
          Id: CFCustomOrigin
          CustomOriginConfig:
            HTTPPort: '80'
            HTTPSPort: '443'
            OriginProtocolPolicy: http-only
        Enabled: 'true'
        DefaultCacheBehavior:
          TargetOriginId: CFCustomOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: ["DELETE", "GET", "HEAD", "OPTIONS", "PATCH", "POST", "PUT"]
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
        PriceClass: PriceClass_200
        ViewerCertificate:
          CloudFrontDefaultCertificate: 'true'

Outputs:

  ApplicationURL:
    Value: !Sub https://${CloudFrontDistribution.DomainName}
    Description: URL for the application
  BastionHostIP:
    Value: !GetAtt BastionHost.Outputs.EIP1
    Description: Public IP for Bastion Host





